DROP TABLE temperature;
DROP TABLE humidity;
DROP TABLE co;
DROP TABLE o3;
DROP TABLE no2;

CREATE TABLE Eggs(
	CosmID INT NOT NULL UNIQUE,
	EggID SERIAL,
	Active BOOLEAN DEFAULT true,
	PRIMARY KEY (CosmID)
	);
	
SELECT AddGeometryColumn('eggs', 'geom', 4326, 'POINT', 2);

CREATE TABLE Temperature(
	TempID SERIAL,
	EggID INT NOT NULL,
	Time TIMESTAMP,
	Temperature NUMERIC,
	Valid BOOLEAN,
	UNIQUE(EggID, Time),
	PRIMARY KEY (TempID),
	FOREIGN KEY (EggID) REFERENCES Eggs
	ON DELETE CASCADE
	ON UPDATE CASCADE
	);
	
CREATE TABLE Humidity(
	HumID SERIAL,
	EggID INT NOT NULL,
	Time TIMESTAMP,
	Humidity NUMERIC,
	Valid BOOLEAN,
	UNIQUE(EggID, Time),
	PRIMARY KEY (HumID),
	FOREIGN KEY (EggID) REFERENCES Eggs
	ON DELETE CASCADE
	ON UPDATE CASCADE
	);

CREATE TABLE CO(
	CoID SERIAL,
	EggID INT NOT NULL,
	Time TIMESTAMP,
	CO NUMERIC,
	Valid BOOLEAN,
	UNIQUE(EggID, Time),
	PRIMARY KEY (CoID),
	FOREIGN KEY (EggID) REFERENCES Eggs
	ON DELETE CASCADE
	ON UPDATE CASCADE
	);

CREATE TABLE O3(
	O3ID SERIAL,
	EggID INT NOT NULL,
	Time TIMESTAMP,
	O3 NUMERIC,
	Valid BOOLEAN,
	UNIQUE(EggID, Time),
	PRIMARY KEY (O3ID),
	FOREIGN KEY (EggID) REFERENCES Eggs
	ON DELETE CASCADE
	ON UPDATE CASCADE
	);


CREATE TABLE NO2(
	NO2ID SERIAL,
	EggID INT NOT NULL,
	Time TIMESTAMP,
	NO2 NUMERIC,
	Valid BOOLEAN,
	UNIQUE(EggID, Time),
	PRIMARY KEY (NO2ID),
	FOREIGN KEY (EggID) REFERENCES Eggs
	ON DELETE CASCADE
	ON UPDATE CASCADE
	);