CREATE TABLE Eggs(
	CosmID INT NOT NULL UNIQUE,
	EggID SERIAL,
	PRIMARY KEY (CosmID)
	);
	
SELECT AddGeometryColumn('eggs', 'geom', 4326, 'POINT', 2);

CREATE TABLE Temperatur(
	TempID SERIAL,
	EggID INT NOT NULL,
	Time TIMESTAMP,
	Temperatur NUMERIC,
	Valid BOOLEAN,
	PRIMARY KEY (TempID),
	FOREIGN KEY (EggID) REFERENCES Eggs
	ON DELETE CASCADE
	ON UPDATE CASCADE
	);
	
CREATE TABLE Humidity(
	HumID SERIAL,
	EggID INT NOT NULL,
	Time TIMESTAMP,
	Humidity NUMERIC,
	Valid BOOLEAN,
	PRIMARY KEY (HumID),
	FOREIGN KEY (EggID) REFERENCES Eggs
	ON DELETE CASCADE
	ON UPDATE CASCADE
	);

CREATE TABLE CO(
	CoID SERIAL,
	EggID INT NOT NULL,
	Time TIMESTAMP,
	CO INT,
	Valid BOOLEAN,
	PRIMARY KEY (CoID),
	FOREIGN KEY (EggID) REFERENCES Eggs
	ON DELETE CASCADE
	ON UPDATE CASCADE
	);

CREATE TABLE O3(
	O3ID SERIAL,
	EggID INT NOT NULL,
	Time TIMESTAMP,
	O3 INT,
	Valid BOOLEAN,
	PRIMARY KEY (O3ID),
	FOREIGN KEY (EggID) REFERENCES Eggs
	ON DELETE CASCADE
	ON UPDATE CASCADE
	);


CREATE TABLE NO2(
	NO2ID SERIAL,
	EggID INT NOT NULL,
	Time TIMESTAMP,
	NO2 INT,
	Valid BOOLEAN,
	PRIMARY KEY (NO2ID),
	FOREIGN KEY (EggID) REFERENCES Eggs
	ON DELETE CASCADE
	ON UPDATE CASCADE
	);